settings:
  enable-sign: false
  enable-effects: true
  show-icons: true
  effect-rotation-delta: 15
  effect-fragmented-fans: 8
  effect-density: 3
  effect-inner-particle: dragon_breath
  effect-outer-particle: cloud
  effect-interval: 5
  teleport-cooldown: 100
  throw-after-teleport:
    enabled: true
    angle: 60
    power: 1

portals:
  'spawn':
    name: "&a&lSpawn"
    location: "world 0 0 0"
  'home':
    name: "&c&lHome"
    location: "world 100 100 100"
    permission: "back.to.home"
  'shop':
    name: "&e&lShop"
    location: "world 50 50 50"
    icon: emerald
    disabled: true
  'dungeon-entry':
    name: "&e&l>Dungeon<"
    location: "world 30 20 10"
    hide-effects: true
  'dungeon-exit':
    name: "&e&lDungeon"
    location: "dungeon 100 200 300"

tunnels:
  - spawn > home
  - spawn > shop
  - home > shop
