settings:
  enable-sign: false
  enable-effects: true
  show-icons: true
  throwing-velocity-alpha: 60
  effect-rotation-delta: 15
  effect-fragmented-fans: 8
  effect-density: 3
  effect-inner-particle: dragon_breath
  effect-outer-particle: cloud
  effect-interval: 5
  teleport-cooldown: 100

portals:
  'spawn':
    name: "&a&lSpawn"
    location: "world 0 0 0"
  'home':
    name: "&c&lHome"
    location: "world 100 100 100"
    permission: "back.to.home"
  'shop':
    name: "&e&lShop"
    location: "world 50 50 50"
    icon: emerald
    disabled: true

tunnels:
  - spawn > home
  - spawn > shop
  - home > shop
