settings:
  enable-sign: false
  enable-effects: true
  show-icons: true
  effect-rotation-delta: 15
  effect-fragmented-fans: 8
  effect-density: 5
  effect-inner-particle: dragon_breath
  effect-outer-particle: cloud

portals:
  'spawn':
    name: "&a&lSpawn"
    location: "world 0 0 0"
  'home':
    name: "&c&lHome"
    location: "world 100 100 100"
  'shop':
    name: "&e&lShop"
    location: "world 50 50 50"
    icon: emerald

tunnels:
  - spawn > home
  - spawn > shop
  - home > shop
